spring.application.name=payments

spring.datasource.url=jdbc:postgresql://ep-late-voice-a1lpgiwo-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ah14uQCmfiPw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


upi.app.jwtSecret=20c6d9055612a582f362b3647ac4f90a8cc61a8706c503900e6fccb00b3fe8b9
upi.app.jwtExpirationMs=86400000 

